/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carros;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author tone
 */
public class FrmCarros extends javax.swing.JFrame {

    /**
     * Creates new form FrmCarros
     */
    public FrmCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        lblChegada = new javax.swing.JLabel();
        lblCar1 = new javax.swing.JLabel();
        lblCar2 = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonStart.setText("START");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));

        lblChegada.setText("Chegada");
        lblChegada.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 25)));
        getContentPane().add(lblChegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 270));

        lblCar1.setText("CAR1");
        lblCar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 125, 27), 10));
        getContentPane().add(lblCar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 80, 40));

        lblCar2.setText("CAR2");
        lblCar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 12), 10));
        getContentPane().add(lblCar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 40));

        lblPista.setText("PISTA");
        lblPista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 890, 270));

        setSize(new java.awt.Dimension(908, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        new Thread(){
            int i = 0;
            public void run(){
                while (lblCar1.getX()>= 70 || lblCar2.getX()>= 70){
                    Random r = new Random();
                    int v1 = r.nextInt(9);
                    int v2 = r.nextInt(9);
                    lblCar1.setLocation(lblCar1.getX() - v1, lblCar1.getY());
                    lblCar2.setLocation(lblCar2.getX() - v2, lblCar2.getY());
                    if(lblCar1.getX()<= 70){
                        JOptionPane.showMessageDialog(rootPane, "O CAR 1 VENCEU!!!");
                        lblCar2.setVisible(false);
                        stop();
                    } else if (lblCar2.getX()<= 70) {
                        JOptionPane.showMessageDialog(rootPane, "O CAR 2 VENCEU!!!");
                        lblCar1.setVisible(false);
                        stop();
                    }
                    try {
                        sleep(60);
                    } catch (Exception e) {
                    }
                    
                }
            }
        }.start();

    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel lblCar1;
    private javax.swing.JLabel lblCar2;
    private javax.swing.JLabel lblChegada;
    private javax.swing.JLabel lblPista;
    // End of variables declaration//GEN-END:variables
}
