/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Dao.DaoMedico;
import model.beans.BeansMedico;
import model.beans.BeansModelTable;
import model.connection.ConnectionBD;

/**
 *
 * @author tone
 */
public class FormMedico extends javax.swing.JFrame {

    BeansMedico modMed = new BeansMedico();
    DaoMedico ctrlMed = new DaoMedico();
    ConnectionBD conn = new ConnectionBD();
    int flag = 0;

    public FormMedico() {
        initComponents();
        preencherTabela("select * from medico order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCRM = new javax.swing.JTextField();
        jComboBoxEspecialista = new javax.swing.JComboBox<>();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedico = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome");

        jLabel3.setText("Nº. CRM");

        jLabel4.setText("Especialista");

        jTextFieldNome.setEnabled(false);

        jTextFieldCRM.setEnabled(false);

        jComboBoxEspecialista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirurgia", "Clinico Geral", "Emergência", "Ortopedia" }));
        jComboBoxEspecialista.setEnabled(false);
        jComboBoxEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialistaActionPerformed(evt);
            }
        });

        jButtonNew.setText("NOVO");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonEdit.setText("ALTERAR");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("EXCLUIR");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSave.setText("SALVAR");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("CANCELAR");
        jButtonCancel.setEnabled(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTableMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedico);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        jTextFieldID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxEspecialista, 0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Médicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(673, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecialistaActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jTextFieldID.setText("");
        jTextFieldCRM.setText("");
        jTextFieldNome.setText("");
        jTextFieldPesquisa.setText("");
        jButtonSave.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jTextFieldCRM.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButtonCancel.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonNew.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome para continuar!");
            jTextFieldNome.requestFocus();
        } else if (jTextFieldCRM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o CRM para continuar!");
            jTextFieldCRM.requestFocus();
        } else {
            if (flag == 1) {
                modMed.setNome(jTextFieldNome.getText());
                modMed.setEspecialidade((String) jComboBoxEspecialista.getSelectedItem());
                modMed.setCrm(Integer.parseInt(jTextFieldCRM.getText()));
                ctrlMed.salvar(modMed);
                jTextFieldCRM.setText("");
                jTextFieldNome.setText("");
                jTextFieldID.setText("");
                jButtonSave.setEnabled(false);
                jTextFieldNome.setEnabled(false);
                jTextFieldCRM.setEnabled(false);
                jComboBoxEspecialista.setEnabled(false);
                jButtonCancel.setEnabled(false);
                jButtonNew.setEnabled(true);
                jTextFieldPesquisa.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
            } else {
                modMed.setCod(Integer.parseInt(jTextFieldID.getText()));
                modMed.setNome(jTextFieldNome.getText());
                modMed.setEspecialidade(String.valueOf(jComboBoxEspecialista.getSelectedItem()));
                modMed.setCrm(Integer.parseInt(jTextFieldCRM.getText()));
                ctrlMed.editar(modMed);
                jTextFieldCRM.setText("");
                jTextFieldNome.setText("");
                jTextFieldPesquisa.setText("");
                jTextFieldID.setText("");
                jButtonSave.setEnabled(false);
                jTextFieldNome.setEnabled(false);
                jTextFieldCRM.setEnabled(false);
                jComboBoxEspecialista.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonNew.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jTextFieldPesquisa.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
            }
        }
        preencherTabela("select * from medico order by nome");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        flag = 1;
        jTextFieldCRM.setText("");
        jTextFieldNome.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldID.setText("");
        jButtonNew.setEnabled(false);
        jButtonSave.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldCRM.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (!jTextFieldPesquisa.getText().isEmpty()) {
            modMed.setPesquisa(jTextFieldPesquisa.getText());
            BeansMedico model = ctrlMed.buscaMedico(modMed);
            if (model.getCod() == 0) {
                jTextFieldCRM.setText("");
                jTextFieldNome.setText("");
                jTextFieldPesquisa.setText("");
                jTextFieldID.setText("");
            } else {

                jTextFieldID.setText(String.valueOf(model.getCod()));
                jTextFieldCRM.setText(String.valueOf(model.getCrm()));
                jTextFieldNome.setText(model.getNome());
                jComboBoxEspecialista.setSelectedItem(model.getEspecialidade());
                jButtonEdit.setEnabled(true);
                jButtonDelete.setEnabled(true);
                preencherTabela("select * from medico where nome like'%" + model.getPesquisa() + "%'");
            }
        } else {
            jButtonEdit.setEnabled(false);
            jButtonNew.setEnabled(true);
            jButtonCancel.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jTextFieldCRM.setText("");
            jTextFieldNome.setText("");
            jTextFieldPesquisa.setText("");
            jTextFieldID.setText("");
            preencherTabela("select * from medico order by nome");
        }


    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        flag = 2;
        jButtonSave.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldCRM.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonNew.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (!jTextFieldID.getText().isEmpty()) {
            int res = 0;
            res = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
            if (res == JOptionPane.YES_OPTION) {
                modMed.setCod(Integer.parseInt(jTextFieldID.getText()));
                ctrlMed.excluir(modMed);
                jTextFieldCRM.setText("");
                jTextFieldNome.setText("");
                jTextFieldPesquisa.setText("");
                jTextFieldID.setText("");
                jButtonSave.setEnabled(false);
                jTextFieldNome.setEnabled(false);
                jTextFieldCRM.setEnabled(false);
                jComboBoxEspecialista.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonNew.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jButtonDelete.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um médico para excluir!");
            jTextFieldPesquisa.requestFocus();
        }
        preencherTabela("select * from medico order by nome");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicoMouseClicked
        String nome = "" + jTableMedico.getValueAt(jTableMedico.getSelectedRow(), 1);
        conn.connect();
        conn.executeSql("select * from medico where nome='" + nome + "'");
        try {
            conn.rs.first();
            jTextFieldID.setText(String.valueOf(conn.rs.getInt("cod")));
            jTextFieldNome.setText(conn.rs.getString("nome"));
            jTextFieldCRM.setText(String.valueOf(conn.rs.getInt("crm")));
            jComboBoxEspecialista.setSelectedItem(conn.rs.getString("especialidade"));
            jButtonEdit.setEnabled(true);
            jButtonDelete.setEnabled(true);
        } catch (SQLException ex) {
            System.out.println("Erro ao selecionar linha \nerro: " + ex.getMessage());
        }
        conn.desconnect();
        jButtonNew.setEnabled(false);
        jButtonCancel.setEnabled(true);
    }//GEN-LAST:event_jTableMedicoMouseClicked

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Especialidade", "CRM"};
        conn.connect();
        conn.executeSql(sql);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getInt("cod"), conn.rs.getString("nome"), conn.rs.getString("especialidade"), conn.rs.getInt("crm")});

            } while (conn.rs.next());

        } catch (SQLException ex) {
            System.out.println("Erro ao preecher arrayList \nerro: " + ex.getMessage());
        }

        BeansModelTable modTable = new BeansModelTable(dados, colunas);

        jTableMedico.setModel(modTable);
        jTableMedico.getColumnModel().getColumn(0).setPreferredWidth(33);
        jTableMedico.getColumnModel().getColumn(0).setResizable(false);
        jTableMedico.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableMedico.getColumnModel().getColumn(1).setResizable(false);
        jTableMedico.getColumnModel().getColumn(2).setPreferredWidth(107);
        jTableMedico.getColumnModel().getColumn(2).setResizable(false);
        jTableMedico.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableMedico.getColumnModel().getColumn(3).setResizable(false);
        jTableMedico.getTableHeader().setReorderingAllowed(false);
        jTableMedico.setAutoResizeMode(jTableMedico.AUTO_RESIZE_OFF);
        jTableMedico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conn.desconnect();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxEspecialista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedico;
    private javax.swing.JTextField jTextFieldCRM;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
