/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Dao.DaoUser;
import model.beans.BeansModelTable;
import model.beans.BeansUser;
import model.connection.ConnectionBD;

/**
 *
 * @author tone
 */
public class FormUser extends javax.swing.JFrame {

    BeansUser modUser = new BeansUser();
    DaoUser ctrlUser = new DaoUser();
    ConnectionBD conn = new ConnectionBD();
    int flag = 0;

    public FormUser() {
        initComponents();
        preencherTabela("select * from usuarios order by user_name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPasswordFieldConfirmSenha = new javax.swing.JPasswordField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Usuário");

        jLabel4.setText("Senha");

        jLabel5.setText("Confirmar senha");

        jLabel6.setText("Tipo");

        jTextFieldUser.setEnabled(false);

        jPasswordFieldSenha.setEnabled(false);

        jPasswordFieldConfirmSenha.setEnabled(false);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "medico", "recepcionista" }));
        jComboBoxTipo.setEnabled(false);

        jButtonSave.setText("Salvar");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonNew.setText("Novo");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Alterar");
        jButtonEdit.setEnabled(false);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Excluir");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.setEnabled(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUser);

        jLabel2.setText("COD");

        jTextFieldID.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordFieldSenha)
                                    .addComponent(jComboBoxTipo, 0, 186, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jTextFieldPesquisa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPesquisar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPasswordFieldConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordFieldConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(766, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        flag = 1;
        jTextFieldUser.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmSenha.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldID.setText("");
        jButtonNew.setEnabled(false);
        jButtonSave.setEnabled(true);
        jTextFieldUser.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfirmSenha.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (jTextFieldUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o usuário para continuar!");
            jTextFieldUser.requestFocus();
        } else if (jPasswordFieldSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a senha para continuar!");
            jPasswordFieldSenha.requestFocus();
        } else if (jPasswordFieldConfirmSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirme a senha para continuar!");
            jPasswordFieldConfirmSenha.requestFocus();
        } else {
            if (flag == 1) {
                modUser.setUsername(jTextFieldUser.getText());
                modUser.setTipo((String) jComboBoxTipo.getSelectedItem());
                modUser.setPassword(jPasswordFieldSenha.getText());
                ctrlUser.salvar(modUser);
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmSenha.setText("");
                jTextFieldUser.setText("");
                jButtonSave.setEnabled(false);
                jTextFieldUser.setEnabled(false);
                jPasswordFieldSenha.setEnabled(false);
                jPasswordFieldConfirmSenha.setEnabled(false);
                jComboBoxTipo.setEnabled(false);
                jButtonCancel.setEnabled(false);
                jButtonNew.setEnabled(true);
                jTextFieldPesquisa.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
            } else {
                modUser.setCod(Integer.parseInt(jTextFieldID.getText()));
                modUser.setUsername(jTextFieldUser.getText());
                modUser.setTipo(String.valueOf(jComboBoxTipo.getSelectedItem()));
                modUser.setPassword(jPasswordFieldSenha.getText());
                ctrlUser.editar(modUser);
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmSenha.setText("");
                jTextFieldUser.setText("");
                jTextFieldPesquisa.setText("");
                jTextFieldID.setText("");
                jButtonSave.setEnabled(false);
                jTextFieldUser.setEnabled(false);
                jPasswordFieldSenha.setEnabled(false);
                jPasswordFieldConfirmSenha.setEnabled(false);
                jComboBoxTipo.setEnabled(false);
                jButtonEdit.setEnabled(false);
                jButtonNew.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jTextFieldPesquisa.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
            }
        }
        preencherTabela("select * from usuarios order by user_name");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jTextFieldID.setText("");
        jPasswordFieldConfirmSenha.setText("");
        jPasswordFieldSenha.setText("");
        jTextFieldUser.setText("");
        jTextFieldPesquisa.setText("");
        jButtonSave.setEnabled(false);
        jTextFieldUser.setEnabled(false);
        jPasswordFieldConfirmSenha.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jComboBoxTipo.setEnabled(false);
        jButtonCancel.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonNew.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        flag = 2;
        jButtonSave.setEnabled(true);
        jTextFieldUser.setEnabled(true);
        jPasswordFieldConfirmSenha.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonEdit.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonNew.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo pesquisa para continuar!");
            jTextFieldPesquisa.requestFocus();
        } else {
            modUser.setPesquisa(jTextFieldPesquisa.getText());
            BeansUser model = ctrlUser.buscaUser(modUser);
            if (model.getCod() == 0) {
                jPasswordFieldConfirmSenha.setText("");
                jPasswordFieldSenha.setText("");
                jTextFieldUser.setText("");
                jTextFieldPesquisa.setText("");
                jTextFieldID.setText("");
            } else {
                jTextFieldID.setText(String.valueOf(model.getCod()));
                jTextFieldUser.setText(model.getUsername());
                jComboBoxTipo.setSelectedItem(model.getTipo());
                jButtonEdit.setEnabled(true);
                jButtonDelete.setEnabled(true);
                preencherTabela("select * from usuarios where user_name like'%"+model.getPesquisa()+"%'");
            }
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int res = 0;
        res = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (res == JOptionPane.YES_OPTION) {
            modUser.setCod(Integer.parseInt(jTextFieldID.getText()));
            ctrlUser.excluir(modUser);
            jTextFieldID.setText("");
            jPasswordFieldConfirmSenha.setText("");
            jPasswordFieldSenha.setText("");
            jTextFieldUser.setText("");
            jTextFieldPesquisa.setText("");
            jButtonSave.setEnabled(false);
//            jTextFieldNome.setEnabled(false);
//            jTextFieldCRM.setEnabled(false);
//            jComboBoxEspecialista.setEnabled(false);
            jButtonEdit.setEnabled(false);
            jButtonNew.setEnabled(true);
            jButtonCancel.setEnabled(false);
            jButtonDelete.setEnabled(false);

            jButtonSave.setEnabled(false);
            jTextFieldUser.setEnabled(false);
            jPasswordFieldConfirmSenha.setEnabled(false);
            jPasswordFieldSenha.setEnabled(false);
            jComboBoxTipo.setEnabled(false);
            jButtonCancel.setEnabled(false);
            jButtonEdit.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonNew.setEnabled(true);
//            jTextFieldPesquisa.setEnabled(true);
//            jButtonPesquisar.setEnabled(true);
            preencherTabela("select * from usuarios order by user_name");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        String nome = "" + jTableUser.getValueAt(jTableUser.getSelectedRow(), 1);
        conn.connect();
        conn.executeSql("select * from usuarios where user_name='" + nome + "'");
        try {
            conn.rs.first();
            jTextFieldID.setText(String.valueOf(conn.rs.getInt("cod")));
            jTextFieldUser.setText(conn.rs.getString("user_name"));
            jPasswordFieldSenha.setText(conn.rs.getString("pass"));
            jComboBoxTipo.setSelectedItem(conn.rs.getString("tipo"));
            jButtonEdit.setEnabled(true);
            jButtonDelete.setEnabled(true);
        } catch (SQLException ex) {
            System.out.println("Erro ao selecionar linha \nerro: " + ex.getMessage());
        }
        conn.desconnect();
        jButtonNew.setEnabled(false);
        jButtonCancel.setEnabled(true);
    }//GEN-LAST:event_jTableUserMouseClicked
    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Username", "Senha", "Tipo"};
        conn.connect();
        conn.executeSql(sql);
        try {
            conn.rs.first();
            do {
                dados.add(new Object[]{conn.rs.getInt("cod"), conn.rs.getString("user_name"), conn.rs.getString("pass"), conn.rs.getString("tipo")});

            } while (conn.rs.next());

        } catch (SQLException ex) {
            System.out.println("Erro ao preecher arrayList \nerro: " + ex.getMessage());
        }

        BeansModelTable modTable = new BeansModelTable(dados, colunas);

        jTableUser.setModel(modTable);
        jTableUser.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableUser.getColumnModel().getColumn(0).setResizable(false);
        jTableUser.getColumnModel().getColumn(1).setPreferredWidth(273);
        jTableUser.getColumnModel().getColumn(1).setResizable(false);
        jTableUser.getColumnModel().getColumn(2).setPreferredWidth(207);
        jTableUser.getColumnModel().getColumn(2).setResizable(false);
        jTableUser.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableUser.getColumnModel().getColumn(3).setResizable(false);
        jTableUser.getTableHeader().setReorderingAllowed(false);
        jTableUser.setAutoResizeMode(jTableUser.AUTO_RESIZE_OFF);
        jTableUser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conn.desconnect();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
