/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.connection.ConnectionBD;

/**
 *
 * @author tone
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConnectionBD connecta = new ConnectionBD();
    FormUser telaUser = new FormUser();
    FormMedico telaMedico = new FormMedico();

    public TelaPrincipal(String user) {
        initComponents();
        jLabelUser.setText(user);
        connecta.connect();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadMed = new javax.swing.JButton();
        jButtonCadEnf = new javax.swing.JButton();
        jButtonCadPaci = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabelPanelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCad = new javax.swing.JMenu();
        jMenuItemCadMed = new javax.swing.JMenuItem();
        jMenuItemCadPaci = new javax.swing.JMenuItem();
        jMenuItemCadEnf = new javax.swing.JMenuItem();
        jMenuItemCadUser = new javax.swing.JMenuItem();
        jMenuRela = new javax.swing.JMenu();
        jMenuFerra = new javax.swing.JMenu();
        jMenuItemFerraTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setClosable(true);
        jInternalFrameBemVindo.setTitle("Bem - Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabel2.setText("Cadastros -");
        jPanelInterno.add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 17);

        jButtonCadMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CadMedicos.png"))); // NOI18N
        jButtonCadMed.setToolTipText("Médicos");
        jButtonCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadMed);
        jButtonCadMed.setBounds(10, 40, 80, 90);

        jButtonCadEnf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-infermeira.png"))); // NOI18N
        jButtonCadEnf.setToolTipText("Enfermeiras");
        jButtonCadEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEnfActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadEnf);
        jButtonCadEnf.setBounds(90, 40, 70, 90);

        jButtonCadPaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadPacientes.png"))); // NOI18N
        jButtonCadPaci.setToolTipText("Pacientes");
        jPanelInterno.add(jButtonCadPaci);
        jButtonCadPaci.setBounds(160, 40, 80, 90);

        jLabel3.setText("Agenda -");
        jPanelInterno.add(jLabel3);
        jLabel3.setBounds(10, 140, 70, 17);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agenda.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Agendamentos");
        jPanelInterno.add(jButtonAgenda);
        jButtonAgenda.setBounds(10, 160, 110, 110);

        jLabelPanelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internalframe.png"))); // NOI18N
        jPanelInterno.add(jLabelPanelFundo);
        jLabelPanelFundo.setBounds(0, 0, 760, 300);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 70, 760, 300);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 16)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de: ");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 250, 20);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 30, 770, 400);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 770, 430);
        getContentPane().add(jLabelUser);
        jLabelUser.setBounds(70, 430, 230, 20);

        jLabel4.setText("Usuário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 430, 70, 20);

        jMenuCad.setText("Cadastros");

        jMenuItemCadMed.setText("Médicos");
        jMenuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItemCadMed);

        jMenuItemCadPaci.setText("Pacientes");
        jMenuCad.add(jMenuItemCadPaci);

        jMenuItemCadEnf.setText("Enfermeiras");
        jMenuCad.add(jMenuItemCadEnf);

        jMenuItemCadUser.setText("Usuários");
        jMenuItemCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUserActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItemCadUser);

        jMenuBar1.add(jMenuCad);

        jMenuRela.setText("Relatorios");
        jMenuBar1.add(jMenuRela);

        jMenuFerra.setText("Ferramentas");

        jMenuItemFerraTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemFerraTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFerraTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerra.add(jMenuItemFerraTelaBemVindo);

        jMenuBar1.add(jMenuFerra);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(781, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        connecta.desconnect();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemFerraTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFerraTelaBemVindoActionPerformed
        jInternalFrameBemVindo.setVisible(true);

    }//GEN-LAST:event_jMenuItemFerraTelaBemVindoActionPerformed

    private void jMenuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedActionPerformed

        try {
            connecta.executeSql("select * from usuarios where user_name='" + jLabelUser.getText() + "'");
            connecta.rs.first();
            if (connecta.rs.getString("tipo").equals("administrador")) {
                if (telaMedico == null) {
                    telaMedico = new FormMedico();
                    telaMedico.setVisible(true);
                    telaMedico.setResizable(false);
                } else {
                    telaMedico.setVisible(true);
                    telaMedico.setResizable(false);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Contacte o administrador para cadastrar novo médico!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao validar usuário");

        }

    }//GEN-LAST:event_jMenuItemCadMedActionPerformed

    private void jButtonCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedActionPerformed
        try {
            connecta.executeSql("select * from usuarios where user_name='" + jLabelUser.getText() + "'");
            connecta.rs.first();
            if (connecta.rs.getString("tipo").equals("administrador")) {
                if (telaMedico == null) {
                    telaMedico = new FormMedico();
                    telaMedico.setVisible(true);
                    telaMedico.setResizable(false);
                } else {
                    telaMedico.setVisible(true);
                    telaMedico.setResizable(false);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Contacte o administrador para cadastrar novo médico!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao validar usuário");

        }
    }//GEN-LAST:event_jButtonCadMedActionPerformed

    private void jMenuItemCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUserActionPerformed
        try {
            connecta.executeSql("select * from usuarios where user_name='" + jLabelUser.getText() + "'");
            connecta.rs.first();
            if (connecta.rs.getString("tipo").equals("administrador")) {
                if (telaUser == null) {
                    telaUser = new FormUser();
                    telaUser.setVisible(true);
                    telaUser.setResizable(false);
                } else {
                    telaUser.setVisible(true);
                    telaUser.setResizable(false);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Contacte o administrador para cadastrar novo médico!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao validar usuário");

        }

    }//GEN-LAST:event_jMenuItemCadUserActionPerformed

    private void jButtonCadEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEnfActionPerformed

    }//GEN-LAST:event_jButtonCadEnfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnf;
    private javax.swing.JButton jButtonCadMed;
    private javax.swing.JButton jButtonCadPaci;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPanelFundo;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCad;
    private javax.swing.JMenu jMenuFerra;
    private javax.swing.JMenuItem jMenuItemCadEnf;
    private javax.swing.JMenuItem jMenuItemCadMed;
    private javax.swing.JMenuItem jMenuItemCadPaci;
    private javax.swing.JMenuItem jMenuItemCadUser;
    private javax.swing.JMenuItem jMenuItemFerraTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRela;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
